### ISSUE TITLE
Dead link in documentation page

### ISSUE THREAD

**Issue by hgoumner** [abstractqqq/polars_ds_extension#103]
Hello,

First of all thanks a lot for the work you've put into this great tool. I'd like to report that the link to the comprehensive walk-through (basics.ipynb) does not work - https://polars-ds-extension.readthedocs.io/en/latest/examples/basics.ipynb.

Regards,

Hristo

**Comment by abstractqqq** [comment]
you are right.. This points to the basics.ipynb file in examples which you can find on github.. This is obviously not the best way to manage it, but is quite convenient. I will fix it as soon as I get off work

**Comment by abstractqqq** [comment]
It should be fixed. Thanks!
