### ISSUE TITLE
Syntax Warning when importing

### ISSUE THREAD

**Issue by matquant14** [abstractqqq/polars_ds_extension#120]
Just installed latest version and when I import the library, I get:

```python
import polars as pl
import polars_ds as pds

SyntaxWarning: invalid escape sequence '\d' expr = expr.str.extract_all("(\d*\.?\d+)")
```

Looks to be occuring in the str2,py module, on line 91.  If i alter the code to 

```python

expr = expr.str.extract_all(r"(\d*\.?\d+)")
```
It seems to remove that warning.

**Comment by abstractqqq** [comment]
It has been fixed by another user like you! Will be in the next release!

**Comment by abstractqqq** [comment]
Btw, a huge update is coming which includes a lot of syntax changes that benefit end user experience, and linters can now recognize what's in the package. 

This will likely be released either today or tomorrow.

**Comment by matquant14** [comment]
Thanks.  Looking forward to see what's new...
