### ISSUE TITLE
Availability on conda forge?

### ISSUE THREAD

**Issue by ilyanoskov** [abstractqqq/polars_ds_extension#130]
Dear Maintainers,

Thanks a lot for this amazing project. Could you please also publish it to conda forge?

Thank you very much in advance

**Comment by abstractqqq** [comment]
@ilyanoskov 

Apparently someone published it on Conda forge for me without me knowing lol. I have asked them clarify the situation but the package should be downloadable on Conda now :)

https://github.com/conda-forge/polars-ds-feedstock/issues/16
