### ISSUE TITLE
no str2

### ISSUE THREAD

**Issue by willros** [abstractqqq/polars_ds_extension#138]
Using the latest polars-ds version I get the following error

```
AttributeError: 'Expr' object has no attribute 'str2'. Did you mean: 'str'?
```

Any ideas?
Thanks for a great project!

Using:
```
polars==0.20.22
polars_ds==0.4.2
```
MacOS, M1 Sonoma

William

**Comment by abstractqqq** [comment]
In latest releases, I have replaced the old pl.col('c').str2.method_call() by a new method that linters can catch.

You can see more at:
https://github.com/abstractqqq/polars_ds_extension/releases/tag/v0.4.0

All strings methods here can now be called from pds if you import polars_ds as pds:
https://github.com/abstractqqq/polars_ds_extension/blob/main/python/polars_ds/str2.py

**Comment by willros** [comment]
Thanks,

Sorry for missing that.

William
