### ISSUE TITLE
Fail to run with polars 0.19.14

### ISSUE THREAD

**Issue by symb10z** [abstractqqq/polars_ds_extension#16]
When running with polars 0.19.14 getting error:
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: DlSym { desc: "/home/user/somecode/polars_ds_extension/python/polars_ds/_polars_ds.cpython-310-x86_64-linux-gnu.so: undefined symbol: _polars_plugin_get_version" }

**Comment by abstractqqq** [comment]
> When running with polars 0.19.14 getting error:
> 
> pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: DlSym { desc: "/home/user/somecode/polars_ds_extension/python/polars_ds/_polars_ds.cpython-310-x86_64-linux-gnu.so: undefined symbol: _polars_plugin_get_version" }

I am aware of this. Polars 0.19.14 was just released and depends on Rust Polars 0.35 and I haven't made the update.Current I am stuck with some overtime work and I will  likely update later tonight

**Comment by abstractqqq** [comment]
https://github.com/abstractqqq/polars_ds_extension/pull/18
