### ISSUE TITLE
Implement a rolling least squares method.

### ISSUE THREAD

**Issue by Mateuscvieira** [abstractqqq/polars_ds_extension#193]
In the example notebook we see rolling OLS done in the .rolling() context, and the text itself says it's a little slow. Well, [polars_ols](https://github.com/azmyrajab/polars_ols/) has an optimized version of least squares regression using an updating algorithm instead of reestimating at every window. 

I know from reading previous issues that work on OLS is low priority, but this seems like a pretty straight forward job of porting the algorithm to this module's structure, so maybe we should give it a go? For economics and finance work, rolling OLS is one of the most used models, so it would be a very nice feature to have integrated here.

**Comment by abstractqqq** [comment]
Of course! Hands are tied on KNN right now unfortunately... 

Just curious, what is in polars_ds that is not in polars_ols? And what makes you want to port polars_ols's functionality over? Do you think some consolidation will be great for the polars + data science community?

**Comment by Mateuscvieira** [comment]
Yeah, I don't think it's too healthy to have hyperspecific polars extensions like something for OLS itself, but more so domain specific packages, like data science, time series analysis, econometrics, etc... 
I could see an extension separate from polars_ds being focused around econometrics, for example, and then integrating more stuff specific to OLS, like statistics on the coefficients themselves, panel econometrics... Something like plm does on R, as opposed to forecast/tidyverts.

Nothing against that package, though, I currently have it running on production in my job and it's been great. I just miss native and intentional integration with more of the data science toolset.

**Comment by abstractqqq** [comment]
I will start with L2 and L1 regularization, and then move on to rolling regression

**Comment by abstractqqq** [comment]
L1, L2 are done. Will start working on rolling this weekend. The first version will probably more restricted, e.g. no null values input columns... There is a small chance that it will be in the v0.5.1 release. Stay tuned.

**Comment by abstractqqq** [comment]
A very early implementation: https://github.com/abstractqqq/polars_ds_extension/pull/221
Only supports very basic null policy right now. Skip null is not supported yet.

**Comment by abstractqqq** [comment]
I am closing it for now. Some more skipping options, rolling l2, etc,. will be added.
