### ISSUE TITLE
Is it possible to use polars_ds_extention in rust-polars directly?

### ISSUE THREAD

**Issue by wuzhe1234** [abstractqqq/polars_ds_extension#196]
Is it possible to use polars_ds_extention in rust-polars directly?

**Comment by abstractqqq** [comment]
As far as I know, there is no easy way to directly port the package and its expressions to Rust, despite being written in Rust. However, I think it is possible. You might need to look into the proc macro that defines custom expressions and look into how polars registers its expressions. A better place to ask this question may be the polars discord

**Comment by wuzhe1234** [comment]
> As far as I know, there is no easy way to directly port the package and its expressions to Rust, despite being written in Rust. However, I think it is possible. You might need to look into the proc macro that defines custom expressions and look into how polars registers its expressions. A better place to ask this question may be the polars discord

Thanks for you reply, I'll look into proc macro to solve this.
