### ISSUE TITLE
improving performance

### ISSUE THREAD

**Issue by ritchie46** [abstractqqq/polars_ds_extension#2]
Nice to see this plugins taking off!

To get more performance out of polars, it is recommended to not use the Iterators on ChunkedArray, but rather try to use `apply_generic`, `binary_elementwise`, binary_elementwise_values` etc.

These functions will monomorphize and ensure we iterate AND apply in the most performant matter.

**Comment by abstractqqq** [comment]
@ritchie46 

Do you mean something like this? 

```
let op = |x:Option<&str>| {
    if let Some(s) = x {
        Some(levenshtein_dist(s, r))
    } else {
        None
    }
}; 
let out: UInt32Chunked = ca1.apply_generic(op);
```

I noticed that this is slower than using par_iter, but is slighly faster than using iterator as you said.

**Comment by ritchie46** [comment]
Yes.. but par_iter will be much worse in group-by and window functions. In general, expressions should not do their own parallelism, but polars engine should.

**Comment by abstractqqq** [comment]
> Yes.. but par_iter will be much worse in group-by and window functions. In general, expressions should not do their own parallelism, but polars engine should.

Yep. I understand. I think maybe providing a parallel flag with the same warning as in Polars is the way to go. By default, I will keep it false.
