### ISSUE TITLE
support aggregations with query_knn_ptwise

### ISSUE THREAD

**Issue by ignacio-amaya-rovio** [abstractqqq/polars_ds_extension#231]
I was testing the function `query_knn_ptwise` doing a select over some subgroups and I was expecting that for each group a separate kd-tree would be created and only neighbours from within that group would be found. However that does not seem to be the case.

Sample code:
```
df.select(
    pds.query_knn_ptwise(
        pl.col("var1"), pl.col("var2"), pl.col("var3"), 
        index = "id",
        k = 3, 
        dist = "l2",
        parallel = True
    ).over("dimension") 
)
```

Is it so that this function is not supposed to be used in aggregations?

The same thing happens if used with group_by and agg.

I am using polars 1.2.1 and polars_ds 0.5.1

**Comment by abstractqqq** [comment]
It is a mistake by me. You can modify the source code in knn_queries.py and get the right results. This will be patched. The reason is that I misunderstood what `is_elementwise` meant in Polars. (I learned what it meant like a few weeks ago but forgot to patch the code). Thank you for the catch!

```
    if return_dist:
        return pl_plugin(
            symbol="pl_knn_ptwise_w_dist",
            args=cols,
            kwargs=kwargs,
            pass_name_to_apply=True,
            # is_elementwise=True, # remove this. Add the line above
        )
    else:
        return pl_plugin(
            symbol="pl_knn_ptwise",
            args=cols,
            kwargs=kwargs,
            pass_name_to_apply=True,
            # is_elementwise=True, # remove this. Add the line above
        ) 
```

**Comment by ignacio-amaya-rovio** [comment]
Thanks! That solve the issue 😄
