### ISSUE TITLE
d_levenshtein fails with cyrillic words

### ISSUE THREAD

**Issue by symb10z** [abstractqqq/polars_ds_extension#24]
Builded release v0.1.3
d_levenshtein fails with cyrillic words, while levenshtein works fine.

```python
import polars as pl
from polars_ds import StrExt
word_pairs=pl.DataFrame(
    {
        "char1":['Иванко'],
        "char2":['Петрунко']
    }
)
word_pairs=word_pairs.with_columns(pl.col("char1").str_ext.d_levenshtein(pl.col("char2"),parallel=True).alias("distance_ds"))
print(word_pairs)
``` 
Here is error:

```shell
thread '<unnamed>' panicked at /home/symbioz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rapidfuzz-0.3.0/src/details/growing_hashmap.rs:118:19:
index out of bounds: the len is 8 but the index is 61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The plugin panicked which is unrecoverable. Polars will abort
Aborted
```

**Comment by symb10z** [comment]
This was fixed in RapidFuzz
[https://github.com/maxbachmann/rapidfuzz-rs/issues/4](url)
Localy rebuilded with rapidfuzz 0.3.2 and it works fine now.

**Comment by abstractqqq** [comment]
> This was fixed in RapidFuzz
> 
> [https://github.com/maxbachmann/rapidfuzz-rs/issues/4](url)
> 
> Localy rebuilded with rapidfuzz 0.3.2 and it works fine now.

Thank you. I am on vacation rn and will update it once I come back

**Comment by abstractqqq** [comment]
closed https://github.com/abstractqqq/polars_ds_extension/pull/25
