### ISSUE TITLE
Your examples/tutorials are great

### ISSUE THREAD

**Issue by firmai** [abstractqqq/polars_ds_extension#262]
![image](https://github.com/user-attachments/assets/7c6e7d8d-7faf-410f-adb4-2dde6bceab5f)

I learn the most from your examples and tutorials, I think if you keep focusing on them it would be helpful. Also how did you create this its so pretty?

**Comment by abstractqqq** [comment]
The underlying package is great_tables, which is an optional dependency. Polars now has native integration with great_tables. Thank you! I need to work on DIA module a bit more. It hasn't been updated in a while. Now polars has native integration with Atlair, which is a good plotting backend. I was using plotly for some other plots but may switch over one day.
