### ISSUE TITLE
Assistance with Rolling Fitting Using Specified Training and Testing Windows

### ISSUE THREAD

**Issue by ChaunceyDong** [abstractqqq/polars_ds_extension#271]
Hi,

Thank you for creating this helpful tool.

I would like to perform rolling fitting with a specified training window and testing window.
For example, with `train_win`=3 and `test_win`=1:
Using `[0, 1, 2]` to fit and then predict `[3]`.

Is there an easy way to achieve this?

Thanks!

**Comment by abstractqqq** [comment]
What is the next fit and test going to be? Fit on [1,2,3] and test on [4]?

**Comment by ChaunceyDong** [comment]
lets say the time series: [ 1 2 3 4 5 6 7], with train size 3 and test size 2:

```
Train -> Test
1 2 3 -> 4 5
   2 3 4 -> 5 6
      3 4 5 -> 6 7

```

**Comment by abstractqqq** [comment]
I assume you are talking about the OnlineLR (online linear regression class) in the package. It is a very custom process and I do not intend to build this kind of iterators into the package.... First we generate some random data. This kind of stuff, it is better to do with NumPy matrices imo. So I will cast dataframe to NumPy matrices.

```python
import polars_ds as pds
import polars as pl

size = 5000
df = (
    pds.frame(size=size)
    .select(
        pds.random(0.0, 1.0).alias("x1"),
        pds.random(0.0, 1.0).alias("x2"),
        pds.random(0.0, 1.0).alias("x3"),
    )
    .with_columns(
        y1 = pl.col("x1") + pl.col("x2") * 0.2 - 0.3 * pl.col("x3"),
        y2 = pl.col("x1") * 0.1 + pl.col("x2") * 0.15 - 0.1 * pl.col("x3"),
        y3 = pl.col("x1") * 0.5 + pl.col("x2") * 0.3 - 0.2 * pl.col("x3"),
    )
)

X = df.select("x1", "x2", "x3").to_numpy()
y = df.select("y1").to_numpy()
```

Now, the key is to understand what `update` does on this class. It removes/adds impact from a record with a scale c measuring the impact. For the most common use case, c = 1 means add the impact from the new x and new y and c = -1 means remove the impact from the given x and y.

```python

from polars_ds.linear_models import OnlineLR

lr = OnlineLR(fit_bias = False)

period = 10
fit_len = 7

for i in range(0, X.shape[0] - period + 1):
    if i == 0:
        lr.fit(X[:fit_len], y[:fit_len]) # Initial fit
        test_pred = lr.predict(X[fit_len: period]) # Predict on the first period
    else:
        # To roll, we need to know what to forget and what to add
        j = i - 1
        forget_x, forget_y = X[j], y[j]
        latest_x, latest_y = X[j + period], y[j + period]
        # first remove the impact from forget_x, forget_y
        lr.update(forget_x, forget_y, -1)
        # add the impact of the new data
        lr.update(latest_x, latest_y, 1)
        # predict on test
        test_pred = lr.predict(X[i+fit_len: i+period])

    # Do whatever you want with predictions on test
    print(test_pred)
```


By the way, I found some not-so-obvious bugs when writing this answer. A PR is in the process and the code may not run if you have version <= v0.6. I will try and patch it as soon as possible and publish v0.6.1

**Comment by ChaunceyDong** [comment]
Thank you very much!

**Comment by ChaunceyDong** [comment]
actually there is a typo in my previous
