### ISSUE TITLE
Have lstsq_report return same number of rows

### ISSUE THREAD

**Issue by deanm0000** [abstractqqq/polars_ds_extension#59]
There are two issues with the way it is. The first is that the behavior is inconsistent between select and group_by

For example

```
df=pl.DataFrame(
    [
        pl.Series("y", [1.1, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=pl.Float64),
        pl.Series("x", [2.0, 4.0, 5.5, 7.7, 11.0, 13.0], dtype=pl.Float64),
        pl.Series("group", [1, 1, 1, 2, 2, 2], dtype=pl.Int64),
        pl.Series("x2", [1.5, 3.9, 4.9, 7.0, 10.4, 14.0], dtype=pl.Float64),
    ]
)

# then can do
df.select(
    pl.col('y').num.lstsq_report('x', add_bias=True)
).unnest('y')

# but not
(
    df
    .group_by('group')
    .agg(y=pl.col('y').num.lstsq_report('x', add_bias=True))
    .unnest('y')
)

#must insert an explode
(
    df
    .group_by('group')
    .agg(y=pl.col('y').num.lstsq_report('x', add_bias=True))
    .explode('y')
    .unnest('y')
)
```

The other issue is that it's hard to go from that to predictions and by extension r^2

As such it'd be nice if the return was just a really wide struct.

Here's the output I think would be best (granted a bunch of these would be in a struct and need to be unnested

```
df.with_columns(
    report=pl.col('y').num.lstsq_report(*(x_vars:=[pl.col('x'), pl.col('x2')]), add_bias=(add_bias:=True)).implode()
).with_columns(    
    *[pl.col('report').list.get(i).struct.field('coeff').alias(f"coeff_{x.meta.output_name()}")
    for i,x in enumerate(x_vars)],
    *[pl.col('report').list.get(i).struct.field('p>|t|').alias(f"p_{x.meta.output_name()}")
                                                               for i,x in enumerate(x_vars)],
    (pl.col('report').list.last().struct.field('coeff') if add_bias else pl.lit(0)).alias('coeff_const'),
    (pl.col('report').list.last().struct.field('p>|t|') if add_bias else pl.lit(1)).alias('p_const'),
).drop('report')
shape: (6, 10)
┌─────┬──────┬───────┬──────┬───┬──────────┬──────────┬─────────────┬──────────┐
│ y   ┆ x    ┆ group ┆ x2   ┆ … ┆ p_x      ┆ p_x2     ┆ coeff_const ┆ p_const  │
│ --- ┆ ---  ┆ ---   ┆ ---  ┆   ┆ ---      ┆ ---      ┆ ---         ┆ ---      │
│ f64 ┆ f64  ┆ i64   ┆ f64  ┆   ┆ f64      ┆ f64      ┆ f64         ┆ f64      │
╞═════╪══════╪═══════╪══════╪═══╪══════════╪══════════╪═════════════╪══════════╡
│ 1.1 ┆ 2.0  ┆ 1     ┆ 1.5  ┆ … ┆ 0.075954 ┆ 0.594557 ┆ 0.283096    ┆ 0.357684 │
│ 2.0 ┆ 4.0  ┆ 1     ┆ 3.9  ┆ … ┆ 0.075954 ┆ 0.594557 ┆ 0.283096    ┆ 0.357684 │
│ 3.0 ┆ 5.5  ┆ 1     ┆ 4.9  ┆ … ┆ 0.075954 ┆ 0.594557 ┆ 0.283096    ┆ 0.357684 │
│ 4.0 ┆ 7.7  ┆ 2     ┆ 7.0  ┆ … ┆ 0.075954 ┆ 0.594557 ┆ 0.283096    ┆ 0.357684 │
│ 5.0 ┆ 11.0 ┆ 2     ┆ 10.4 ┆ … ┆ 0.075954 ┆ 0.594557 ┆ 0.283096    ┆ 0.357684 │
│ 6.0 ┆ 13.0 ┆ 2     ┆ 14.0 ┆ … ┆ 0.075954 ┆ 0.594557 ┆ 0.283096    ┆ 0.357684 │
└─────┴──────┴───────┴──────┴───┴──────────┴──────────┴─────────────┴──────────┘
```

On your end you wouldn't need to have the constant if add_bias was False, I just did it that way b/c I couldn't think of how to exclude it within the with_columns

**Comment by abstractqqq** [comment]
For the first part, I don't think it is a problem to require an extra explode step in the group by context. This behavior is modeled after polars's native expression that change lengths, e.g. value_counts or unique.

The reason I cannot put variable names as field name in a struct is that in group_by, or rolling context, the series that get passed in will be anonymous, meaning that if the expression is called in group_by, then in the code, when I do series.name() I get empty string, despite the fact that the whole series is named "x".  There are some reasons in the rust code why we must have valid names and so I am naming them "1" to "n" right now..

When you say r^2 do you mean the r^2 metric for model scores?

**Comment by deanm0000** [comment]
Firstly, let me take a step back and say thank you for making this and I appreciate your hard work that you put out for the community.

On the consistency per group, I really don't think there are any native expressions that return something other than 1, or n rows per group. I'm not complaining about the need for `.explode` in the `group_by` context, rather I'm suggesting the `select` case should also return a list so that both need an explode. That said, my next suggestion would cancel this out anyway.

The inability to do field naming, I get it, no worries. It'd still be nice if it were wide instead of long. So basically the same as I said above except it'd be `coeff_0, coeff_1, coeff_2` instead of with the name.

On r^2, yes I meant the metric. 

Bringing everything together, I think having a `returns` parameter to address that we don't have a global model from which to extract things. For instance, I rarely care about std_err or t. I sometimes care about r^2 and residuals or others. As-is, to get those other outputs takes two calls one to `lstsq_report` and one to `lstsq` which means it's doing double the regressions. Maybe it could look like:

```
df.select(
    report=pl.col('y').num.lstsq('x','x2', add_bias=True, returns=['coef','pval','resid','r2', 'std_err','t'])
).unnest('report')
```

I think you'd take out the `return_pred` parameter of `lstsq` and people would only use `lstsq` as a concise way to get the coefficients only as a list and then `lstsq_report` is kind of like the "advanced" version that gives custom output.


The return of it would be a single-row struct with all those fields. For coef, t, std_err, and pval it'd be coef_0, coef_1, etc to go with the index of the X var.

**Comment by abstractqqq** [comment]
All good and no need to be formal here. 

To have the user select what to be returned is slightly hard, if you want to save compute. The easiest way is still to compute all in the Rust code, and then select the ones the user specifies. It is tricky because t depends on the std_err, and p depends on t, etc.. In the end, computing std_err, t, etc. is still relatively cheap...


> The return of it would be a single-row struct with all those fields. For coef, t, std_err, and pval it'd be coef_0, coef_1, etc to go with the index of the X var.

And yes, this probably is the best output format for users.

**Comment by deanm0000** [comment]
yeah I know p doesn't come for free. Preventing the t and std_err from being returned is more about avoiding clutter and copies given that they get a column for every regressor. For things like r^2 and residuals, the current api design requires the user do the regression twice which is the bigger compute savings I'm thinking about.

**Comment by abstractqqq** [comment]
There is a return_pred flag now. Not perfect, but I guess it satisfies most cases when a prediction is needed..
