### ISSUE TITLE
Polars 20.6 breaks strings module - but requirement map to latest polars version

### ISSUE THREAD

**Issue by furlat** [abstractqqq/polars_ds_extension#62]
When calling the notebook 
```python
df2.select(
    pl.col("sen").str.to_lowercase().str2.tokenize(stem=True).explode().unique()
)
```
```
thread '<unnamed>' panicked at crates/polars-lazy/src/physical_plan/exotic.rs:39:65:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot call plugin\n\nThis Polars' version has a different 'binary/string' layout. Please compile with latest 'pyo3-polars'\n\nError originated just after this operation:\nDF [\"\"]; PROJECT */1 COLUMNS; SELECTION: \"None\""))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by furlat** [comment]
i fixed forcing in the pyproject.toml 
```
dependencies = [    
    "polars == 0.20.5",
] 
```

Also
num.py was not registering some methods throwing error in the notebook that have forward type hints using np. without importing numpy i solved by adding import numpy as np and recompiled I can run the full notebook (also from the graph branch) - will test the graphs methods soon

**Comment by furlat** [comment]
Should I wait to test out the graphs method on the next refactor? Or is it useful if I play around the current more_graph branch today?

**Comment by abstractqqq** [comment]
Better wait I think. A lot of exciting stuff coming up. E.g shortest path with unequal distance cost per edge, parallel execution of graph queries, etc. Meanwhile I really appreciate you reading the source code like you ate doing. So keep the questions coming. Thank you

**Comment by abstractqqq** [comment]
Fyi, current main is the release candidate. I want to wait for a few days before release in case I want to make any additional changes or I find any other bugs. But all functionality should be more or less final.
